package com.xelops.actionplan.enumeration.notification;

public enum NotificationTemplateEnum {
    NEW_BOARD_CREATED,
    NEW_BOARD_CREATED_NOTIF,
    USER_INVITED_TO_BOARD,
    USER_INVITED_TO_WORKSPACE,
    USER_INVITED_TO_BOARD_NOTIF,
    USER_INVITED_TO_WORKSPACE_NOTIF,
    USER_MENTIONED_IN_ACTION_NOTIF,
    USER_MENTIONED_IN_ACTION,
    USER_ASSIGNED_IN_ACTION_NOTIF,
    USER_ASSIGNED_IN_ACTION
}
